### ISSUE TITLE
Collaboration and communication tools

### ISSUE THREAD

**Issue by javgh** [hivewallet/discussions#2]
I wanted to open this issue to discuss how we want to organize communication and collaboration within the team going forward and what some good practices could be. I'm not interested in defining any "rules" and maybe nothing much needs to be changed, but I think it would be helpful to get a feeling for what everyone prefers and have some guidelines as to how to keep the signal to noise ratio high.

Current tools:
- Emails
- Skype group chat
- GitHub issues (for specific software modules, as well as meta topics like this)
- Etherpads
- GitHub wikis
- Weekly calls via Skype or appear.in
- BitTorrent Sync (sparingly, from what I can tell)

My input:
- I would like to make the case for switching from Skype group chat to IRC. For a number of reasons:
  - out of principle, with Skype being proprietary
  - I worry that Skype for Linux will turn into abandonware 
  - Skype on Linux is somewhat buggy, crashes occasionally
  - I find notification settings for Skype fairly limited. Maybe I haven't figured out all the tricks (the Linux version also tends to have fewer features), but I would think that IRC clients are more customizable in this regard. I like to read the backlog from time to time and only get instant notifications when my name is mentioned.
- We could simply use a channel on Freenode. Maybe have #hivewallet be a public channel for everyone to join and then use #hivewallet-team as a password-protected channel for internal discussions. And maybe also #hivewallet-team-watercooler for chit chat
- I think the Etherpads should probably be retired. They feel like a loose collection of papers lying around somewhere. Maybe some of the stuff can be moved into GitHub wikis or, when it shouldn't be public, into BitTorrent Sync. I guess Etherpads can be very useful for spontaneous document creation as a group, but then should be archived somewhere more permanent afterwards.
- I personally like mailing lists as a discussion platform. I think it would be helpful, if we could create something like team@hivewallet.com to make emailing the whole team easier.
- I do not have personally experience with it, but I was wondering if something like Trello could be helpful to maintain a very high-level view of current activities. The detailed stuff would still be in GitHub issues, but the more strategic planning could be a few cards in Trello. I don't feel strongly about this though, just an idea.

**Comment by mackuba** [comment]
Ah, it's the old "what do we replace Skype with" discussion again... how many times I went through this with various teams... ;)

Personally, I'm totally fine with the current setup:
- emails for longer discussions, like the Android plans, App Store implementation etc., or threads just like this one :)
- GitHub issues for public discussions about specific features
- GitHub wiki is for public and rather static documents, like the API docs or coding guidelines
- Skype for everything else, for more instant and synchronous communication

BitTorrent Sync isn't really used anymore, it was mostly used for sharing builds before GitHub, and for sharing mockups, images and other design stuff, but it isn't now for obvious reasons...

As for EtherPad, there's only two things we've used it for, that one high-level plan document by Wendell and the meeting minutes that Wei started to write. I guess we could move this somewhere if it bothers you, but I don't care really. Maybe it could be moved to a wiki in a private repo. (Actually, this repo could be private too...)

+1 for a mailing list that would save me selecting those 6-7 people manually every time I want to write an email to everyone.

I'm not sure about Trello, I feel like having two parallel places with a list of tasks would be redundant and annoying to maintain...

-1 for IRC, mostly because I don't use it at all, I don't even have a proper client installed... Also, what about reading what other people wrote when you weren't online?

As for Skype notifications, have you tried this http://softobase.com/article/skype-secrets-hidden-chat-commands ? (I only found this now, I usually just use right click -> Notification Settings if I need to)

I would be fine with switching from Skype to Hipchat/Campfire/etc. if that makes someone happier, since they have native apps and work pretty much in the same way as Skype (except the p2p annoyances like not getting old messages because there's no one to send them to you).

**Comment by javgh** [comment]
Good point regarding offline messages. I did not think of that, I guess
that would be a big disadvantage/problem with IRC.

I think having a private wiki would be a good thing. The minutes could
go there and also some kind of agenda for the next meeting, to be built
up during the week.

Making this repository private and thereby having the issues and wiki
private would requires us to upgrade our GitHub plan, right? But yes,
maybe we should just do that. The cheapest option seems to be $25 per
month.

**Comment by ghost** [comment]
Closing for the time being; I think our tools are OK for now.
