### ISSUE TITLE
Promoting BitcoinKit

### ISSUE THREAD

**Issue by ghost** [hivewallet/discussions#21]
Since @mikehearn is working on integrating a JVM into BitcoinKit, it would probably be advisable for us to start promoting its use wide and far, in order to make our fundraiser around that more successful.

I only know of one other wallet that is currently using BitcoinKit, and that is @jonasschnelli 's own. Anyone know of any others?

**Comment by ghost** [comment]
@jsuder @nschum Would you guys be willing to write some pieces for the Mac technical (and maybe nontechnical) media about this, and generally becoming evangelists for BitcoinKit?

**Comment by mackuba** [comment]
I'm afraid I'm not confident enough about its state to start actively promoting it... I mean, I'm not saying it's in bad shape, it works fine for us, but to treat it as something that I can safely recommend to everyone I'd have to improve the docs and comments, merge some improvements from Jonas's fork, do some refactoring and other tweaks that I generally don't have time for now... Maybe even start versioning it somehow, because right now we basically change whatever we want whenever we want without any regard for backwards compatibility.

**Comment by ghost** [comment]
Closing/backburnering this for now in that case.
